name: release
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Setup golang version
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
          
      - name: Check and release
        run: |
            rm -fr *
            sudo apt update
            sudo apt install upx git -y
            git clone https://github.com/Scaleya/hugo.git _hugo > /dev/null
            cd _hugo
            GOOS=linux GOARCH=amd64 go build --tags extended -o hugo -trimpath -ldflags "-s -w -buildid=" main.go 
            upx -9 hugo
            cp hugo ..
            cd ..
            shopt -s extglob
            rm -vrf !("hugo")
            git init
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "hugo-"
            git push origin main --force
